package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import peliasetusrekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.10 17:50:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** testIterator72 */
  @Test
  public void testIterator72() {    // Joukkueet: 72
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(); joukkueet.lisaa(pitsi11); 
    Joukkue pitsi22 = new Joukkue(); joukkueet.lisaa(pitsi22); 
    Joukkue pitsi12 = new Joukkue(); joukkueet.lisaa(pitsi12); 
    Joukkue pitsi23 = new Joukkue(); joukkueet.lisaa(pitsi23); 
    Iterator<Joukkue> i2=joukkueet.iterator(); 
    assertEquals("From: Joukkueet line: 84", pitsi21, i2.next()); 
    assertEquals("From: Joukkueet line: 85", pitsi11, i2.next()); 
    assertEquals("From: Joukkueet line: 86", pitsi22, i2.next()); 
    assertEquals("From: Joukkueet line: 87", pitsi12, i2.next()); 
    assertEquals("From: Joukkueet line: 88", pitsi23, i2.next()); 
    try {
    assertEquals("From: Joukkueet line: 89", pitsi12, i2.next()); 
    fail("Joukkueet: 89 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue104 */
  @Test
  public void testAnnaJoukkue104() {    // Joukkueet: 104
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue("pitsi21"); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(); joukkueet.lisaa(pitsi11); 
    assertEquals("From: Joukkueet line: 110", pitsi21, joukkueet.annaJoukkue(1)); 
  } // Generated by ComTest END
}