package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import peliasetusrekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.01 04:35:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista90 
   * @throws SailoException when error
   */
  @Test
  public void testPoista90() throws SailoException {    // Joukkueet: 90
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(); pitsi21.taytaJoukkueTiedoilla(); 
    Joukkue pitsi11 = new Joukkue(); pitsi11.taytaJoukkueTiedoilla(); 
    Joukkue pitsi22 = new Joukkue(); pitsi22.taytaJoukkueTiedoilla(); 
    Joukkue pitsi12 = new Joukkue(); pitsi12.taytaJoukkueTiedoilla(); 
    Joukkue pitsi23 = new Joukkue(); pitsi23.taytaJoukkueTiedoilla(); 
    joukkueet.lisaa(pitsi21); 
    joukkueet.lisaa(pitsi11); 
    joukkueet.lisaa(pitsi22); 
    joukkueet.lisaa(pitsi12); 
    assertEquals("From: Joukkueet line: 103", false, joukkueet.poista(pitsi23)); assertEquals("From: Joukkueet line: 103", 4, joukkueet.getLkm()); 
    assertEquals("From: Joukkueet line: 104", true, joukkueet.poista(pitsi11)); assertEquals("From: Joukkueet line: 104", 3, joukkueet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta118 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta118() throws SailoException {    // Joukkueet: 118
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue ence1 = new Joukkue(); 
    Joukkue ence2 = new Joukkue(); 
    File tied = new File("joukkueet.dat"); 
    tied.delete(); 
    try {
    joukkueet.lueTiedostosta(); 
    fail("Joukkueet: 126 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    joukkueet.lisaa(ence1); 
    joukkueet.lisaa(ence2); 
    joukkueet.tallenna(); 
    joukkueet = new Joukkueet(); 
    joukkueet.lueTiedostosta(); 
    Iterator<Joukkue> i = joukkueet.iterator(); 
    assertEquals("From: Joukkueet line: 133", ence1.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 134", ence2.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 135", false, i.hasNext()); 
    joukkueet.lisaa(ence1); 
    joukkueet.tallenna(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator201 */
  @Test
  public void testIterator201() {    // Joukkueet: 201
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(); joukkueet.lisaa(pitsi11); 
    Joukkue pitsi22 = new Joukkue(); joukkueet.lisaa(pitsi22); 
    Joukkue pitsi12 = new Joukkue(); joukkueet.lisaa(pitsi12); 
    Joukkue pitsi23 = new Joukkue(); joukkueet.lisaa(pitsi23); 
    Iterator<Joukkue> i2=joukkueet.iterator(); 
    assertEquals("From: Joukkueet line: 213", pitsi21, i2.next()); 
    assertEquals("From: Joukkueet line: 214", pitsi11, i2.next()); 
    assertEquals("From: Joukkueet line: 215", pitsi22, i2.next()); 
    assertEquals("From: Joukkueet line: 216", pitsi12, i2.next()); 
    assertEquals("From: Joukkueet line: 217", pitsi23, i2.next()); 
    try {
    assertEquals("From: Joukkueet line: 218", pitsi12, i2.next()); 
    fail("Joukkueet: 218 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue233 */
  @Test
  public void testAnnaJoukkue233() {    // Joukkueet: 233
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(); joukkueet.lisaa(pitsi11); 
  } // Generated by ComTest END
}