package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import peliasetusrekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.10 10:00:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {


  // Generated by ComTest BEGIN
  /** testIterator70 */
  @Test
  public void testIterator70() {    // Joukkueet: 70
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(2); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(1); joukkueet.lisaa(pitsi11); 
    Joukkue pitsi22 = new Joukkue(2); joukkueet.lisaa(pitsi22); 
    Joukkue pitsi12 = new Joukkue(1); joukkueet.lisaa(pitsi12); 
    Joukkue pitsi23 = new Joukkue(2); joukkueet.lisaa(pitsi23); 
    Iterator<Joukkue> i2=joukkueet.iterator(); 
    assertEquals("From: Joukkueet line: 82", pitsi21, i2.next()); 
    assertEquals("From: Joukkueet line: 83", pitsi11, i2.next()); 
    assertEquals("From: Joukkueet line: 84", pitsi22, i2.next()); 
    assertEquals("From: Joukkueet line: 85", pitsi12, i2.next()); 
    assertEquals("From: Joukkueet line: 86", pitsi23, i2.next()); 
    try {
    assertEquals("From: Joukkueet line: 87", pitsi12, i2.next()); 
    fail("Joukkueet: 87 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Joukkue jou : joukkueet ) {
    assertEquals("From: Joukkueet line: 93", jnrot[n], jou.getProfiiliNro()); n++; 
    }
    assertEquals("From: Joukkueet line: 96", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue111 */
  @Test
  public void testAnnaJoukkue111() {    // Joukkueet: 111
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pitsi21 = new Joukkue(2); joukkueet.lisaa(pitsi21); 
    Joukkue pitsi11 = new Joukkue(1); joukkueet.lisaa(pitsi11); 
    Joukkue pitsi22 = new Joukkue(2); joukkueet.lisaa(pitsi22); 
    Joukkue pitsi12 = new Joukkue(1); joukkueet.lisaa(pitsi12); 
    Joukkue pitsi23 = new Joukkue(2); joukkueet.lisaa(pitsi23); 
    Joukkue pitsi51 = new Joukkue(5); joukkueet.lisaa(pitsi51); 
    List<Joukkue> loytyneet; 
    loytyneet = joukkueet.annaJoukkue(3); 
    assertEquals("From: Joukkueet line: 124", 0, loytyneet.size()); 
    loytyneet = joukkueet.annaJoukkue(1); 
    assertEquals("From: Joukkueet line: 126", 2, loytyneet.size()); 
    assertEquals("From: Joukkueet line: 127", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Joukkueet line: 128", true, loytyneet.get(1) == pitsi12); 
    loytyneet = joukkueet.annaJoukkue(5); 
    assertEquals("From: Joukkueet line: 130", 1, loytyneet.size()); 
    assertEquals("From: Joukkueet line: 131", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}