package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.01 04:35:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi81 */
  @Test
  public void testRekisteroi81() {    // Joukkue: 81
    Joukkue pitsi1 = new Joukkue(); 
    assertEquals("From: Joukkue line: 83", 0, pitsi1.getTunnusNro()); 
    pitsi1.rekisteroi(); 
    Joukkue pitsi2 = new Joukkue(); 
    pitsi2.rekisteroi(); 
    int n1 = pitsi1.getTunnusNro(); 
    int n2 = pitsi2.getTunnusNro(); 
    assertEquals("From: Joukkue line: 89", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString144 */
  @Test
  public void testToString144() {    // Joukkue: 144
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("  1  |  Natus Vincere  "); 
    assertEquals("From: Joukkue line: 147", "1|Natus Vincere", joukkue.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse161 */
  @Test
  public void testParse161() {    // Joukkue: 161
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("  1  |  Natus Vincere  "); 
    assertEquals("From: Joukkue line: 164", "1|Natus Vincere", joukkue.toString()); 
    joukkue.rekisteroi(); 
    int n = joukkue.getTunnusNro(); 
    joukkue.parse(""+(n+20)); 
    joukkue.rekisteroi(); 
    assertEquals("From: Joukkue line: 170", n+20+1, joukkue.getTunnusNro()); 
    assertEquals("From: Joukkue line: 171", "" + (n+20+1) + "|Natus Vincere", joukkue.toString()); 
  } // Generated by ComTest END
}