package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.30 06:53:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ProfiilitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa20 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa20() throws SailoException {    // Profiilit: 20
    Profiilit profiilit = new Profiilit(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(); 
    assertEquals("From: Profiilit line: 24", 0, profiilit.getLkm()); 
    profiilit.lisaa(allu1); assertEquals("From: Profiilit line: 25", 1, profiilit.getLkm()); 
    profiilit.lisaa(allu2); assertEquals("From: Profiilit line: 26", 2, profiilit.getLkm()); 
    profiilit.lisaa(allu1); assertEquals("From: Profiilit line: 27", 3, profiilit.getLkm()); 
    assertEquals("From: Profiilit line: 28", allu1, profiilit.anna(0)); 
    assertEquals("From: Profiilit line: 29", allu2, profiilit.anna(1)); 
    assertEquals("From: Profiilit line: 30", allu1, profiilit.anna(2)); 
    assertEquals("From: Profiilit line: 31", false, profiilit.anna(1) == allu1); 
    assertEquals("From: Profiilit line: 32", true, profiilit.anna(1) == allu2); 
    try {
    assertEquals("From: Profiilit line: 33", allu1, profiilit.anna(3)); 
    fail("Profiilit: 33 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    profiilit.lisaa(allu1); assertEquals("From: Profiilit line: 34", 4, profiilit.getLkm()); 
    profiilit.lisaa(allu1); assertEquals("From: Profiilit line: 35", 5, profiilit.getLkm()); 
    try {
    profiilit.lisaa(allu1); 
    fail("Profiilit: 36 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}