package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.01 04:35:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ProfiiliTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi147 */
  @Test
  public void testRekisteroi147() {    // Profiili: 147
    Profiili allu1 = new Profiili(); 
    assertEquals("From: Profiili line: 149", 0, allu1.getTunnusNro()); 
    allu1.rekisteroi(); 
    Profiili allu2 = new Profiili(); 
    allu2.rekisteroi(); 
    int n1 = allu1.getTunnusNro(); 
    int n2 = allu2.getTunnusNro(); 
    assertEquals("From: Profiili line: 155", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString357 */
  @Test
  public void testToString357() {    // Profiili: 357
    Profiili profiili = new Profiili(); 
    profiili.parse("   2  |  allu | 2"); 
    assertEquals("From: Profiili line: 360", true, profiili.toString().startsWith("2|allu|2|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse383 */
  @Test
  public void testParse383() {    // Profiili: 383
    Profiili profiili = new Profiili(); 
    profiili.parse("   2  |  allu | 2"); 
    assertEquals("From: Profiili line: 386", 2, profiili.getTunnusNro()); 
    assertEquals("From: Profiili line: 387", true, profiili.toString().startsWith("2|allu|2|")); 
    profiili.rekisteroi(); 
    int n = profiili.getTunnusNro(); 
    profiili.parse(""+(n+20)); 
    profiili.rekisteroi(); 
    assertEquals("From: Profiili line: 393", n+20+1, profiili.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone414 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone414() throws CloneNotSupportedException {    // Profiili: 414
    Profiili profiili = new Profiili(); 
    profiili.parse("   3  |  allu  | 123"); 
    Profiili kopio = profiili.clone(); 
    assertEquals("From: Profiili line: 419", profiili.toString(), kopio.toString()); 
    profiili.parse("   4  |  allu2   | 123"); 
    assertEquals("From: Profiili line: 421", false, kopio.toString().equals(profiili.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals436 */
  @Test
  public void testEquals436() {    // Profiili: 436
    Profiili profiili1 = new Profiili(); 
    profiili1.parse("   3  |  allu   | 2 "); 
    Profiili profiili2 = new Profiili(); 
    profiili2.parse("   3  |  allu   | 2 "); 
    Profiili profiili3 = new Profiili(); 
    profiili3.parse("   3  |  allu   | 3 "); 
    assertEquals("From: Profiili line: 444", true, profiili1.equals(profiili2)); 
    assertEquals("From: Profiili line: 445", true, profiili2.equals(profiili1)); 
    assertEquals("From: Profiili line: 446", false, profiili1.equals(profiili3)); 
    assertEquals("From: Profiili line: 447", false, profiili3.equals(profiili2)); 
  } // Generated by ComTest END
}