package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import peliasetusrekisteri.SailoException;
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.01 04:35:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {


  // Generated by ComTest BEGIN  // Rekisteri: 16
   private Rekisteri rekisteri; 
   private Profiili allu1; 
   private Profiili allu2; 
   private int pid1; 
   private int pid2; 
   private Joukkue ence1; 
   private Joukkue ence2; 
   private Joukkue ence3; 

   @SuppressWarnings("javadoc")
   public void alustaRekisteri() {
     rekisteri = new Rekisteri(); 
     allu1 = new Profiili(); allu1.taytaAlluTiedoilla(); allu1.rekisteroi(); 
     allu2 = new Profiili(); allu2.taytaAlluTiedoilla(); allu2.rekisteroi(); 
     pid1 = allu1.getTunnusNro(); 
     pid2 = allu2.getTunnusNro(); 
     ence1 = new Joukkue("ence1"); 
     ence2 = new Joukkue("ence2"); 
     ence3 = new Joukkue("ence3"); 
     try {
     rekisteri.lisaa(allu1); 
     rekisteri.lisaa(allu2); 
     rekisteri.lisaa(ence1); 
     rekisteri.lisaa(ence2); 
     rekisteri.lisaa(ence3); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }

  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa58 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa58() throws SailoException {    // Rekisteri: 58
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 63", 0, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 64", 1, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu2); assertEquals("From: Rekisteri line: 65", 2, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 66", 3, rekisteri.getProfiileja()); 
    assertEquals("From: Rekisteri line: 67", allu1, rekisteri.annaProfiili(0)); 
    assertEquals("From: Rekisteri line: 68", allu2, rekisteri.annaProfiili(1)); 
    assertEquals("From: Rekisteri line: 69", allu1, rekisteri.annaProfiili(2)); 
    try {
    assertEquals("From: Rekisteri line: 70", allu1, rekisteri.annaProfiili(3)); 
    fail("Rekisteri: 70 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 71", 4, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 72", 5, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa86 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa86() throws SailoException {    // Rekisteri: 86
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 89", 2, rekisteri.etsi("*",0).size()); 
    rekisteri.korvaaTaiLisaa(allu1); 
    assertEquals("From: Rekisteri line: 91", 2, rekisteri.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista153 
   * @throws Exception when error
   */
  @Test
  public void testPoista153() throws Exception {    // Rekisteri: 153
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 156", 2, rekisteri.etsi("*",1).size()); 
    assertEquals("From: Rekisteri line: 157", 1, rekisteri.poista(allu1)); 
    assertEquals("From: Rekisteri line: 158", 1, rekisteri.etsi("*",1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista173 
   * @throws Exception when error
   */
  @Test
  public void testPoista173() throws Exception {    // Rekisteri: 173
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 176", 6, rekisteri.etsi("*").size()); 
    rekisteri.poista(ence1); 
    assertEquals("From: Rekisteri line: 178", 4, rekisteri.etsi("*").size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi193 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testEtsi193() throws CloneNotSupportedException, SailoException {    // Rekisteri: 193
    alustaRekisteri(); 
    Profiili allu3 = new Profiili(); allu3.rekisteroi(); 
    allu3.setNimi("allu3"); 
    rekisteri.lisaa(allu3); 
    Collection<Profiili> loytyneet = rekisteri.etsi("*allu*",0); 
    assertEquals("From: Rekisteri line: 200", 3, loytyneet.size()); 
    Iterator<Profiili> it = loytyneet.iterator(); 
    assertEquals("From: Rekisteri line: 202", false, it.next() == allu2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue246 */
  @Test
  public void testAnnaJoukkue246() {    // Rekisteri: 246
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(), allu3 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); allu3.rekisteroi(); 
    Joukkue ence1 = new Joukkue("ence1"); rekisteri.lisaa(ence1); 
    Joukkue ence2 = new Joukkue("ence2"); rekisteri.lisaa(ence2); 
    rekisteri.setJoukkue(allu1, ence1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue266 */
  @Test
  public void testAnnaJoukkue266() {    // Rekisteri: 266
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 268", "ence1", rekisteri.annaJoukkue("ence1").getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi282 
   * @throws Exception when error
   */
  @Test
  public void testEtsi282() throws Exception {    // Rekisteri: 282
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 285", 6, rekisteri.etsi("*").size()); 
    rekisteri.poista(ence1); 
    assertEquals("From: Rekisteri line: 287", 4, rekisteri.etsi("*").size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta307 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta307() throws SailoException {    // Rekisteri: 307
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(); allu1.taytaAlluTiedoilla(); allu1.rekisteroi(); 
    Profiili allu2 = new Profiili(); allu2.taytaAlluTiedoilla(); allu2.rekisteroi(); 
    Joukkue ence1 = new Joukkue(); 
    Joukkue ence2 = new Joukkue(); 
    File ftied = new File("profiilit.dat"); 
    File fhtied = new File("joukkueet.dat"); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    rekisteri.lueTiedostosta(); 
    fail("Rekisteri: 323 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence1); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    rekisteri = new Rekisteri(); 
    rekisteri.lueTiedostosta(); 
    Collection<Profiili> kaikki = rekisteri.etsi("",0); 
    Iterator<Profiili> it = kaikki.iterator(); 
    assertEquals("From: Rekisteri line: 333", true, it.hasNext()); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    assertEquals("From: Rekisteri line: 337", true, ftied.delete()); 
    assertEquals("From: Rekisteri line: 338", true, fhtied.delete()); 
  } // Generated by ComTest END
}