package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.31 11:38:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa22 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa22() throws SailoException {    // Rekisteri: 22
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 27", 0, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 28", 1, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu2); assertEquals("From: Rekisteri line: 29", 2, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 30", 3, rekisteri.getProfiileja()); 
    assertEquals("From: Rekisteri line: 31", allu1, rekisteri.annaProfiili(0)); 
    assertEquals("From: Rekisteri line: 32", allu2, rekisteri.annaProfiili(1)); 
    assertEquals("From: Rekisteri line: 33", allu1, rekisteri.annaProfiili(2)); 
    try {
    assertEquals("From: Rekisteri line: 34", allu1, rekisteri.annaProfiili(3)); 
    fail("Rekisteri: 34 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 35", 4, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 36", 5, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJoukkue129 */
  @Test
  public void testAnnaJoukkue129() {    // Rekisteri: 129
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(), allu3 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); allu3.rekisteroi(); 
    Joukkue ence1 = new Joukkue("ence1"); rekisteri.lisaa(ence1); 
    Joukkue ence2 = new Joukkue("ence2"); rekisteri.lisaa(ence2); 
    rekisteri.setJoukkue(allu1, ence1); 
    assertEquals("From: Rekisteri line: 138", ence1, rekisteri.annaJoukkue(allu1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaProfiilit150 */
  @Test
  public void testAnnaProfiilit150() {    // Rekisteri: 150
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(), allu3 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); allu3.rekisteroi(); 
    Joukkue ence1 = new Joukkue("ence1"); rekisteri.lisaa(ence1); 
    Joukkue ence2 = new Joukkue("ence2"); rekisteri.lisaa(ence2); 
    rekisteri.setJoukkue(allu1, ence1); 
    rekisteri.setJoukkue(allu2, ence1); 
    List<Profiili> loytyneet; 
    loytyneet = rekisteri.annaProfiilit(ence2); 
    assertEquals("From: Rekisteri line: 163", 0, loytyneet.size()); 
    rekisteri.setJoukkue(allu3, ence2); 
    loytyneet = rekisteri.annaProfiilit(ence2); 
    assertEquals("From: Rekisteri line: 166", 1, loytyneet.size()); 
    assertEquals("From: Rekisteri line: 167", true, loytyneet.get(0) == allu3); 
    loytyneet = rekisteri.annaProfiilit(ence1); 
    assertEquals("From: Rekisteri line: 169", 2, loytyneet.size()); 
    assertEquals("From: Rekisteri line: 170", true, loytyneet.get(0) == allu1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta181 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta181() throws SailoException {    // Rekisteri: 181
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(); allu1.taytaAlluTiedoilla(); allu1.rekisteroi(); 
    Profiili allu2 = new Profiili(); allu2.taytaAlluTiedoilla(); allu2.rekisteroi(); 
    Joukkue ence1 = new Joukkue(); 
    Joukkue ence2 = new Joukkue(); 
    File ftied = new File("profiilit.dat"); 
    File fhtied = new File("joukkueet.dat"); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    rekisteri.lueTiedostosta(); 
    fail("Rekisteri: 197 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence1); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    rekisteri = new Rekisteri(); 
    rekisteri.lueTiedostosta(); 
    Collection<Profiili> kaikki = rekisteri.etsi("",-1); 
    Iterator<Profiili> it = kaikki.iterator(); 
    assertEquals("From: Rekisteri line: 207", allu1, it.next()); 
    assertEquals("From: Rekisteri line: 208", allu2, it.next()); 
    assertEquals("From: Rekisteri line: 209", false, it.hasNext()); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    assertEquals("From: Rekisteri line: 213", true, ftied.delete()); 
    assertEquals("From: Rekisteri line: 214", true, fhtied.delete()); 
  } // Generated by ComTest END
}