package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.31 18:18:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa21 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa21() throws SailoException {    // Rekisteri: 21
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 26", 0, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 27", 1, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu2); assertEquals("From: Rekisteri line: 28", 2, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 29", 3, rekisteri.getProfiileja()); 
    assertEquals("From: Rekisteri line: 30", allu1, rekisteri.annaProfiili(0)); 
    assertEquals("From: Rekisteri line: 31", allu2, rekisteri.annaProfiili(1)); 
    assertEquals("From: Rekisteri line: 32", allu1, rekisteri.annaProfiili(2)); 
    try {
    assertEquals("From: Rekisteri line: 33", allu1, rekisteri.annaProfiili(3)); 
    fail("Rekisteri: 33 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 34", 4, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); assertEquals("From: Rekisteri line: 35", 5, rekisteri.getProfiileja()); 
    rekisteri.lisaa(allu1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi190 */
  @Test
  public void testEtsi190() {    // Rekisteri: 190
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(), allu2 = new Profiili(), allu3 = new Profiili(); 
    allu1.rekisteroi(); allu2.rekisteroi(); allu3.rekisteroi(); 
    Joukkue ence1 = new Joukkue("ence1"); rekisteri.lisaa(ence1); 
    Joukkue ence2 = new Joukkue("ence2"); rekisteri.lisaa(ence2); 
    rekisteri.setJoukkue(allu1, ence1); 
    rekisteri.setJoukkue(allu2, ence1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta212 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta212() throws SailoException {    // Rekisteri: 212
    Rekisteri rekisteri = new Rekisteri(); 
    Profiili allu1 = new Profiili(); allu1.taytaAlluTiedoilla(); allu1.rekisteroi(); 
    Profiili allu2 = new Profiili(); allu2.taytaAlluTiedoilla(); allu2.rekisteroi(); 
    Joukkue ence1 = new Joukkue(); 
    Joukkue ence2 = new Joukkue(); 
    File ftied = new File("profiilit.dat"); 
    File fhtied = new File("joukkueet.dat"); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    rekisteri.lueTiedostosta(); 
    fail("Rekisteri: 228 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(allu1); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence1); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    rekisteri = new Rekisteri(); 
    rekisteri.lueTiedostosta(); 
    Collection<Profiili> kaikki = rekisteri.etsi("",-1); 
    Iterator<Profiili> it = kaikki.iterator(); 
    assertEquals("From: Rekisteri line: 238", allu1, it.next()); 
    assertEquals("From: Rekisteri line: 239", allu2, it.next()); 
    assertEquals("From: Rekisteri line: 240", false, it.hasNext()); 
    rekisteri.lisaa(allu2); 
    rekisteri.lisaa(ence2); 
    rekisteri.tallenna(); 
    assertEquals("From: Rekisteri line: 244", true, ftied.delete()); 
    assertEquals("From: Rekisteri line: 245", true, fhtied.delete()); 
  } // Generated by ComTest END
}