package peliasetusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import peliasetusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.01 04:35:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SailoExceptionTest {
}